name: ka_gnn_cpu
channels:
  - nvidia
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=1.1.1w
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.11.0
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - annotated-types==0.7.0
      - babel==2.17.0
      - backrefs==5.9
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - cmake==4.1.0
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - dgl==2.1.0
      - filelock==3.19.1
      - fonttools==4.59.2
      - ghp-import==2.1.0
      - idna==3.10
      - jarvis-tools==2023.12.12
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lit==18.1.8
      - logzero==1.7.0
      - markdown==3.9
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - mergedeep==1.3.4
      - mkdocs==1.6.1
      - mkdocs-get-deps==0.2.0
      - mkdocs-material==9.6.20
      - mkdocs-material-extensions==1.3.1
      - mpmath==1.3.0
      - networkx==2.8
      - numpy==1.23.1
      - packaging==25.0
      - paginate==0.5.7
      - pandas==1.4.2
      - pathspec==0.12.1
      - pillow==11.3.0
      - platformdirs==4.4.0
      - psutil==7.0.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pykan==0.2.8
      - pymdown-extensions==10.16.1
      - pyparsing==3.2.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0
      - pyyaml-env-tag==1.1
      - rdkit-pypi==2022.9.5
      - requests==2.32.5
      - ruamel-yaml==0.18.15
      - ruamel-yaml-clib==0.2.12
      - scikit-learn==1.7.2
      - scipy==1.13.1
      - six==1.17.0
      - spglib==2.6.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - toolz==1.0.0
      - torch==2.0.1
      - torchaudio==2.0.2
      - torchdata==0.6.1
      - torchvision==0.15.2
      - tqdm==4.67.1
      - triton==2.0.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - urllib3==2.5.0
      - watchdog==6.0.0
      - xmltodict==1.0.0